[package]
name = "gb-ui-native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.21"
egui = "0.22.0"
egui-wgpu = "0.22.0"
egui-winit = { version = "0.22.0", default-features = false, features = ["links"] }
env_logger = "0.10.0"
gb-core = { path = "../gb-core" }
log = "0.4.20"
pixels = "0.13.0"
winit = "0.28.6"
winit_input_helper = "0.14.1"
