[package]
name = "gb-opcode-info"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.109"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
