[package]
name = "gameboy-emulator-eframe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
bootrom = ["gb-core/bootrom"]
cgb = ["gb-core/cgb"]

[dependencies.gb-core]
path = "../../core/gb-core"

[dependencies]
clap = "4.4.6"
eframe = "0.23.0"
egui = "0.23.0"
env_logger = "0.10.0"
log = "0.4.20"
rfd = { version = "0.12.0", default-features = false, features = ["xdg-portal"] }
