[package]
name = "gb-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# default = ["bootrom", "cgb"]
bootrom = []
cgb = []

[dependencies]
arrayvec = "0.7.4"
bitflags = "2.4.1"
enum_dispatch = "0.3.12"
log = "0.4.20"
paste = "1.0.14"
thiserror = "1.0.50"

[dev-dependencies]
image = { version = "0.24.7", default-features = false, features = ["png"] }
num = { version = "0.4.1", default-features = false }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
