[package]
name = "gb-core-c"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["staticlib"]

[features]
bundled-bootrom = ["gb-core/bundled-bootrom"]

[dependencies]
gb-core = { workspace = true }
