[package]
name = "gameboy-emulator-eframe"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[features]
# default = ["bootrom", "cgb"]
bootrom = ["gb-core/bootrom"]
cgb = ["gb-core/cgb"]

[dependencies.gb-core]
workspace = true

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }
eframe = { version = "0.26.1", default-features = false, features = [
    "wgpu",
    "wayland",
    "x11",
] }
egui = "0.26.1"
env_logger = "0.11.1"
log = "0.4.20"
rfd = { version = "0.13.0", default-features = false, features = [
    "xdg-portal",
    "async-std",  # Required for `xdg-portal`
] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
