[package]
name = "gameboy-emulator-sdl2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# default = ["bootrom", "cgb"]
bootrom = ["gb-core/bootrom"]
cgb = ["gb-core/cgb"]

[dependencies]
clap = "4.4.4"
env_logger = "0.10.0"
gb-core = { path = "../../core/gb-core" }
rfd = "0.12.0"
sdl2 = "0.35.2"
