[package]
name = "gameboy-emulator-sdl2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
bootrom = ["gb-core/bootrom"]
cgb = ["gb-core/cgb"]

[dependencies.gb-core]
path = "../../core/gb-core"

[dependencies]
clap = "4.4.5"
env_logger = "0.10.0"
rfd = { version = "0.12.0", default-features = false, features = ["xdg-portal"] }
sdl2 = "0.35.2"
