[package]
name = "gameboy-emulator-sdl2"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[features]
bootrom = ["gb-core/bootrom"]
cgb = ["gb-core/cgb"]

[dependencies.gb-core]
workspace = true

[dependencies]
clap = "4.4.12"
env_logger = "0.10.1"
log = "0.4.20"
rfd = { version = "0.12.1", default-features = false, features = [
    "xdg-portal",
] }
sdl2 = { version = "0.36.0", features = ["bundled"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
