[package]
name = "gb-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
bootrom = []

[dependencies]
arrayvec = "0.7.4"
bitflags = "2.4.0"
log = "0.4.20"
