[package]
name = "gb-libretro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[features]
# default = ["bootrom", "cgb"]
bootrom = ["gb-core/bootrom"]
cgb = ["gb-core/cgb"]

[dependencies]
env_logger = "0.10.0"
gb-core = { path = "../../core/gb-core", features = ["libretro"] }
libretro-rs = "0.1.3"
log = "0.4.20"
