[package]
name = "gb-libretro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
gb-core = { workspace = true, features = ["libretro"] }
libretro-rs = "0.1.3"
log = "0.4.20"

[lib]
crate-type = ["cdylib"]
