name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install development dependencies for cpal
        run: sudo apt-get install libasound2-dev

      - name: Update Rust toolchain
        run: rustup update

      - name: Build
        run: cargo build --all-targets --verbose

      - name: Run tests
        run: cargo test --all-targets --verbose
