name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Build default
        run: cargo build --verbose

      - name: Run default tests
        run: cargo test --verbose

      - name: Build CGB
        run: cargo build --verbose --features "cgb"

      - name: Run CGB tests
        run: cargo test --verbose --features "cgb"
