name: Vercel Preview Deployment

on:
  push:
    branches-ignore: ["main"]

env:
  CARGO_TERM_COLOR: always
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Update Rust toolchain
        run: rustup update

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Install wasm-pack
        run: npm install -g wasm-pack@latest

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Link Vercel project
        run: vercel link --cwd ./apps/web --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Vercel Environment Information
        run: vercel pull --cwd ./apps/web --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --cwd ./apps/web --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --cwd ./apps/web --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
