name: Vercel Preview Deployment

on:
  push:
    branches-ignore: ["main"]

env:
  CARGO_TERM_COLOR: always
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - name: Install system dependencies
        run: sudo apt install libgtk-3-dev

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Install wasm-pack
        run: npm install -g wasm-pack@latest

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Change to the project folder
        run: cd gb-ui-browser

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
